language: python

services:
  - docker

install:
  - "pip install flake8"

env:
  - AIRFLOW_VERSION=1.10.6
  - AIRFLOW_VERSION=1.10.5
  - AIRFLOW_VERSION=1.10.4
  - AIRFLOW_VERSION=1.10.3

script:
  - flake8
  - make test
